### ISSUE TITLE
already initialized constant RSpec::Support::Mutex

### ISSUE THREAD

**Issue by tjchambers** [rspec/rspec-support#244]
Not sure why others are NOT reporting this, but I am getting:

```
/Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:46: warning: already initialized constant RSpec::Support::Mutex
/Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:46: warning: previous definition of Mutex was here
```

I am using `rspec/mocks` which both core and mocks attempt to load the `reentrant_mutex.rb` support.

My gemfile contains:

```
  gem 'rspec-core',  github: 'rspec/rspec-core'
  gem 'rspec-rails', github: 'rspec/rspec-rails'

  gem 'rspec-mocks', github: 'rspec/rspec-mocks'
  gem 'rspec-support', github: 'rspec/rspec-support'
```

The indicated target lines are:

```ruby
    if defined? ::Mutex
      # On 1.9 and up, this is in core, so we just use the real one
      Mutex = ::Mutex
    else # For 1.8.7
      # :nocov:
      RSpec::Support.require_rspec_support "mutex"
      #
``` 

When I alter to

```ruby
    if defined? ::Mutex
      # On 1.9 and up, this is in core, so we just use the real one
      Mutex ||= ::Mutex
    else # For 1.8.7
      # :nocov:
      RSpec::Support.require_rspec_support "mutex"
      #
```

The attempt to redefine is no longer the case and that _appears_ to solve the problem. Not sure I understand why this is not something all are experiencing.

**Comment by JonRowe** [comment]
This is an issue caused by your environment, if you look at the two lines closely you'll see you have two copies of `rspec-support` (both at the same version) in different locations. Normally when you hit a require if the file name is the same it'll return true and continue onwards, in this case you're getting a double require of the file due to the differing file names and encountering this redefinition error. No one else has reported it yet because they likely don't have the environment to trigger it.

My top of the head suggestion is to add ```gem 'rspec-expectations', github: 'rspec/rspec-expectations'``` to your Gemfile, as you can't generally mix and match git and other dependency based versions of rspec (and in this case rspec-rails will have brought in expectations for you).

Meanwhile we'll have a ponder to see if theres a way we can prevent this. (I don't consider adding `||=` a fix really, it's defensive programming and shouldn't be necessary).

**Comment by tjchambers** [comment]
Thanks for the quick reply. I had not noticed them coming from different locations. 

I already do has rspec-expectations specified as you suggest in my Gemfile. So I need to spec ALL of them as from github I suspect. So I will head that direction and see where it leads.

**Comment by tjchambers** [comment]
It turns out those 2 copies are the same copy - the directories on my gemset which is the default are symlinked. So there is only really one. 

It gets more complicated I think (and I am noob at this). The stack trace for the first assignment of the constant is:

```
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:2:in `<module:RSpec>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:1:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core/memoized_helpers.rb:1:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core.rb:8:in `require_relative'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core.rb:8:in `block in <top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `block in define_optimized_require_for_rspec'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core.rb:37:in `block in <top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core.rb:37:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-core-93e5001b5ae6/lib/rspec/core.rb:37:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:85:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:68:in `block in require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler.rb:134:in `require'
	from /Users/tj/projects/AOT/aotv2/config/application.rb:7:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

And the second assignment (the one that elicits the error) is

```	
from /Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:2:in `<module:RSpec>'
	from /Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support/reentrant_mutex.rb:1:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:28:in `require_relative'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:28:in `block in <module:Support>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `block in define_optimized_require_for_rspec'
	from /Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks/space.rb:1:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks.rb:6:in `require_relative'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks.rb:6:in `block in <top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-support-838e6aab14cd/lib/rspec/support.rb:19:in `block in define_optimized_require_for_rspec'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks.rb:26:in `block in <top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks.rb:26:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks.rb:26:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:85:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:68:in `block in require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.2/lib/bundler.rb:134:in `require'
	from /Users/tj/projects/AOT/aotv2/config/application.rb:7:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

In the second you can see a reference from
```
 /Users/tj/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/bundler/gems/rspec-mocks-abb875d2cc10/lib/rspec/mocks/space.rb:1
```

which directly requires the specific reentrant_mutex.rb using a different approach. So it still looks to me like this is a case where there are two paths that lead to requiring the same module. 

Thoughts?

**Comment by tjchambers** [comment]
I am not disputing that using `||=` is a protective measure, but if multiple modules require this code directly, is that not a useful measure?

**Comment by JonRowe** [comment]
No because the require should only be evaluated once, so the bug lies elsewhere.

**Comment by myronmarston** [comment]
Can you put together a reproducible example?

**Comment by myronmarston** [comment]
So I realized what's going on.  The bug is that the file is loaded twice, and the warning is simply a symptom of the bug.  Switching to `||=` would have silenced the fact that we had this bug and it's far better to not load the file twice.

I think I have a working solution for that in rspec/rspec-core#2082.  Do you mind updating your Gemfile to use that commit and let us know if it fixes the problem?

**Comment by tjchambers** [comment]
@myronmarston Sure - I just returned to try and make a reproducible "simple example". I will not be able to do this until morning Pacific Time tomorrow, but I appreciate the support. I was thinking it could be a bug in require_relative vs. require since they both are being used. Will report on my success/failure in AM.

**Comment by tjchambers** [comment]
That appears to have resolved it after using master branch on both rspec-support and rspec-core (to make them in sync). 

Thanks very much.
