### ISSUE TITLE
Ripper formatting doesn't work on jruby-9.2.0.0

### ISSUE THREAD

**Issue by BrianHawley** [rspec/rspec-support#399]
### Ripper formatting doesn't work on jruby-9.2.0.0

When you have a failing assertion that, due to its syntax, calls `RSpec::Support::Source#ast`, and you're running on jruby-9.2.0.0, Ripper.sexp will fail if the code you're calling has keyword arguments because of jruby/jruby#5209. This effectively means that Ripper is not supported by JRuby < 9.2.1.0.

Could you extend the Ripper unsupported jruby version range to include 9.2.0.0? It currently tops out at 9.1.8.0. I haven't checked newer 9.1.x.x versions.

### Your environment
* Ruby version: jruby-9.2.0.0
* rspec-support version: 3.9.2

### Steps to reproduce
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.9.0"
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe "Hello world!" do
  def hi!(**args)
    raise "Hi!"
  end
  it { expect { hi! }.to raise_error(ArgumentError) }
end
```

### Expected behavior
```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using bundler 2.1.4
Using diff-lcs 1.3
Using rspec-support 3.9.2
Using rspec-core 3.9.1
Using rspec-expectations 3.9.0
Using rspec-mocks 3.9.1
Using rspec 3.9.0
Ruby version is: 2.5.0
F

Failures:

  1) Hello world! is expected to raise ArgumentError
     Failure/Error: it { expect { hi! }.to raise_error(ArgumentError) }

       expected ArgumentError, got #<RuntimeError: Hi!> with backtrace:
         # blah_spec.rb:21:in `hi!'
         # blah_spec.rb:23:in `block in blah_spec.rb'
         # blah_spec.rb:23:in `block in blah_spec.rb'
     # blah_spec.rb:23:in `block in blah_spec.rb'

Finished in 0.05447 seconds (files took 0.28638 seconds to load)
1 example, 1 failure

Failed examples:

rspec blah_spec.rb:23 # Hello world! is expected to raise ArgumentError
```

### Actual behavior
```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using bundler 2.1.4
Using diff-lcs 1.3
Using rspec-support 3.9.2
Using rspec-core 3.9.1
Using rspec-expectations 3.9.0
Using rspec-mocks 3.9.1
Using rspec 3.9.0
Ruby version is: 2.5.0
F

NoMethodError: undefined method `on_kwrest_param' for #<Ripper::SexpBuilderPP:0x73c5b676>
                                       parse at org/jruby/ext/ripper/RubyRipper.java:343
                                        sexp at /Users/bhawley/.rvm/rubies/jruby-9.2.0.0/lib/ruby/stdlib/ripper/sexp.rb:33
                                         ast at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-support-3.9.2/lib/rspec/support/source.rb:45
                        nodes_by_line_number at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-support-3.9.2/lib/rspec/support/source.rb:61
            location_nodes_at_beginning_line at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:118
                             expression_node at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:96
  line_range_of_location_nodes_in_expression at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:88
                    line_range_of_expression at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:57
                            expression_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:42
                 extract_expression_lines_at at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/snippet_extractor.rb:31
                           read_failed_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:218
                   failure_slash_error_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:163
                      block in failure_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:150
                                         tap at org/jruby/RubyKernel.java:1876
                               failure_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:149
                     colorized_message_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:34
             formatted_message_and_backtrace at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:240
                       fully_formatted_lines at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:86
                             fully_formatted at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/exception_presenter.rb:78
                             fully_formatted at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/notifications.rb:200
    block in fully_formatted_failed_examples at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/notifications.rb:114
                                        each at org/jruby/RubyArray.java:1801
                             each_with_index at org/jruby/RubyEnumerable.java:1180
             fully_formatted_failed_examples at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/notifications.rb:113
                               dump_failures at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/formatters/base_text_formatter.rb:32
                             block in notify at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:209
                                        each at org/jruby/RubyArray.java:1801
                                      notify at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:208
                             block in finish at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:178
                                 close_after at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:194
                                      finish at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:174
                                      report at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/reporter.rb:76
                                   run_specs at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:115
                                         run at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:89
                                         run at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:71
                                      invoke at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:45
                             perform_at_exit at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:38
                            block in autorun at /Users/bhawley/.rvm/gems/jruby-9.2.0.0@test/gems/rspec-core-3.9.1/lib/rspec/core/runner.rb:24
```

**Comment by pirj** [comment]
Pull request is welcome!
I suggest adding a `push` for another version range here:
https://github.com/rspec/rspec-support/blob/54f601f68cb9cea90ef0b8302fc180f39224a1a0/lib/rspec/support/ruby_features.rb#L114
Please consider adding a spec for this as well, something similar to https://github.com/rspec/rspec-support/blob/54f601f68cb9cea90ef0b8302fc180f39224a1a0/spec/rspec/support/ruby_features_spec.rb#L138
